### ISSUE TITLE
Scraped position data incorrect when user has more than one position in same company

### ISSUE THREAD

**Issue by web-goddess** [linkedtales/scrapedin#103]
The profile shown here has multiple roles at the same company, "Excelian | Luxoft Financial Services".

![Screen Shot 2020-06-09 at 7 45 46 pm](https://user-images.githubusercontent.com/5946286/84132985-e2c4a100-aa89-11ea-8102-2449daabd699.png)

In the scraped profile, both of these roles are collapsed into a single one, where the company name is listed as the title and no companyName field is present. The dates shown are from the first role, but the description is from the second.

```
positions: [
    {
      title: 'Excelian | Luxoft Financial Services',
      link: 'https://www.linkedin.com/company/excelian/',
      url: 'https://www.linkedin.com/company/excelian/',
      location: 'Sydney, Australia',
      description: 'Mxml developer focused on confirmation work',
      date1: 'Sep 2016 – Present',
      date2: '3 yrs 10 mos'
    },
```

**Comment by grapevineai** [comment]
Roles used to work but it's now broken for me too...

**Comment by grapevineai** [comment]
@leonardiwagner I'd love to help here but I don't understand how selectors and templates work. Is there any documentation about how the page is parsed?

If I understand how parsing works, I can also improve the contact info object https://github.com/linkedtales/scrapedin/issues/105

**Comment by leonardiwagner** [comment]
That was fixed on v`1.0.20` please update your version, feedback is appreciated! Thanks for reporting that @web-goddess

**Comment by leonardiwagner** [comment]
@grapevineai all of the scrapping is based on [profileScraperTemplate.js](https://github.com/linkedtales/scrapedin/blob/master/src/profile/profileScraperTemplate.js):

- `template` is an array of LinkedIn sections object, each object will be translated to be the final scrapedin result to the user, it has basically 2 properties:
  - `selector`: a css selector which is an HTML container element which represents a LinkedIn section, such as Education or About.
  - `fields`: it can be two options:
       - `String`:  a CSS selector that will actually scrap an HTML element value to store and return to the user. It can be two options:
       - `Object`: will do recursively do the same job in the current section. It's necessary when we have "elements inside other elements" such as roles from LinkedIn's positions/experiences

It's all based on CSS selectors as you can see, it's not hard. The rest of the code is mostly to read that template and it barely has bugs. Thank you for your contribution, I spend my time here doing this project without earning a single penny so it's good to have help, thank you :smile:

**Comment by grapevineai** [comment]
@leonardiwagner Thank you very much! I know you're doing this on a volunteer base and it's very nice of you to share your work with all of us...

**Comment by web-goddess** [comment]
Fantastic - thanks so much @leonardiwagner !

**Comment by zilti** [comment]
This bug is back again. The selector changed, it is - at least in the redesign - `pv-entity__company-summary-info` that has to be in the `:not` pseudo-selector.
